cli/objects/jira_base.py, cli/report/report.py, cli/templates/jira.config.j2, docs/cli_usage_guide.md, tox.ini
**How Are Duplicate Bugs Handled?**
This tool take duplicate bugs into consideration. When a failure is identified, after the failure has been matched with its corresponding rule in the firewatch config, the firewatch tool with search Jira for any bugs that match the following rules to determine if it is a duplicate:
- Any OPEN issues that are in the same Jira project defined in the rule's `jira_project` key
- **AND** issues that have a label matching the step/pod name that failed
- **AND** issues that have a label matching the prow job name that failed
- **AND** issues that have a label matching the `failure_type` of the failure we are searching for
If any issues are found that match all the conditions above, we can be fairly confident that the failure may be a duplicate and the tool …
=> [LPTOCPCI-281] Add logic to avoid duplicate bugs, but still report on the failure

README.md, cli/objects/jira_base.py, cli/report/report.py, docs/cli_usage_guide.md
This PR allows us to specify an optional epic to file issues under using a `jira_epic` key, for example:
```json
[
{"step": "*ends-with-this", "failure_type": "test_failure", "classification": "Test failures", "jira_project": "TEST", "jira_epic": "EPIC-123"},
]
```
> **IMPORTANT:**
> Any epic you use must have the automation user you are using set as a contributor in Jira. For OpenShift CI, the user is `interop-test-jenkins interop-test-jenkins`. 
This PR also fixes a small bug that did not allow issues to be filed if the classification had spaces in it. The issue was that a tag was being added to the issue that was the value of the classification. The API does not allow spaces in labels.
=> [LPTOCPCI-288] Add logic for issues to be filed under an epic

cli/report/report.py
Found an issue where some test cases may not have results in them. This PR fixes this issue by checking that the cases have results before utilizing that attribute. This PR also fixes a typo in the link to the firewatch repository left in the description of bugs.
=> [LPTOCPCI-308] Issue Parsing XML JUnit XML from ODO Tests

README.md, cli/objects/jira_base.py, cli/report/report.py, docs/cli_usage_guide.md
This PR allows us to specify an optional component to file issues under using the `jira_component` key, for example:
```json
[
{"step": "exact-step-name", "failure_type": "pod_failure", "classification": "Infrastructure", "jira_project": "PROJECT", "jira_component": "some-component"},
]
```
=> [LPTOCPCI-236] Add logic to allow for issues created to be assigned a component

cli/report/report.py
This pull requests adds a try/except block to fix the logic around parsing JUnit results files. Previously, the code assumed any artifact with "junit" in the name would be a results file. Now it will try to parse those files, but if it fails it will print a message and continue.
=> [LPTOCPCI-358] Fix JUnit Parsing Logic

README.md, cli/objects/configuration.py, cli/objects/jira_base.py, cli/objects/job.py, cli/objects/rule.py, cli/report/report.py, docs/configuration_guide.md, tests/unittests/test_firewatch_objects_rule.py
**Modifications**
- **[70081a9](https://github.com/CSPI-QE/firewatch/pull/23/commits/70081a9c967bf6fdfc0324ec21c5775f866da18a)**: Slightly modified the way the firewatch configuration is handled. I noticed that there wasn't any error handling or validation around obtaining the default project or the firewatch config.
**New Features**
- **[fc28391](https://github.com/CSPI-QE/firewatch/pull/23/commits/fc28391df98feee7eef38873f3d6119f839cadf6)**: I have added the new optional field `jira_assignee`. This field allows users to specify which Jira user bugs should be filed under. The value must be the email address of the user they would like to assign bugs to.
- **[b9ffee5](https://github.com/CSPI-QE/firewatch/pull/23/commits/b9ffee5513c7a5acbb57b79c7155776a3291239e)**: I have added the new …
=> [LPTOCPCI-548] Allow to specify priority and assignee

README.md, cli/report/report.py, docs/cli_usage_guide.md
This pull request adds some functionality to the `firewatch report` command.
Now when no failures are found, firewatch will search for any open issues in the provided Jira server. If a open Jira issue is found that matches the passing Prow job, a comment will be made on the open issue, notifying the engineer working on the issue that it may not be relevant anymore. 
Comment example (please ignore my previous tests to nail down the formatting):
**Note:** There is also an option for uses to ignore these notifications on certain issues if they would like. All they need to do is add the `ignore-passing-notification` label to the issue they would like stop notifications for.
=> [LPTOCPCI-578] Add Notification of Passed Job to Open Tickets for That Job

cli/objects/job.py
This pull request fixes a bug that causes firewatch to encounter an error when downloading junit files with duplicate names. The fix will add a suffix to new files with duplicate names to avoid this error.
=> [LPTOCPCI-599] Fix FileExistsError When Downloading Files if a Duplicate is Found in Artifacts Folder

cli/jira_config_gen/__init__.py, cli/jira_config_gen/jira_config_gen.py
Remove unused variables.
Remove try:except from `def token`, click check if the file exists and we need to raise if we failed and not return `str` on error.
=> Cleanup jira_config_jen code

README.md, cli/objects/jira_base.py, cli/report/report.py, tests/unittests/test_firewatch_report.py
This pull request updates the description of new bugs to include a list of up to 10 of the most recent past bugs from a specific step and failure_type. For example, if `step-1` has had a `pod_failure` failure type 5 types in the past and a new bug is being filed, the issue description of the new bug will include a table of those bugs in order of date create. 
Here is an example of the new description in the stage environment:
=> [Issue #83] Include a list of past bugs of a specific step/failure_type in description of new bugs

.pre-commit-config.yaml, cli/jira_config_gen/__init__.py, cli/report/__init__.py, cli/report/report.py, development/test.sh, docs/CONTRIBUTING.md, docs/cli_usage_guide.md, docs/configuration_guide.md
This PR will convert all the underscores to hyphens in the commands and arguments to make firewatch more user-friendly in the command line.
> NOTE:
> 
> This change will not affect firewatch in OpenShift CI yet. This is part of some maintence that needs to be done. Once the maintenance is done, I will switch the OpenShift CI from the `release-v1` branch back to the `main` branch.
=> [Issue #53] Change Commands and Arguments to Use a Hyphen Rather Than an Underscore

README.md, cli/objects/rule.py, docs/configuration_guide.md, tests/unittests/test_firewatch_objects_rule.py
This PR changes the allowed "type" of the `jira_component` value to only be a list of strings to avoid confusion and for consistency. Previously, it allowed a string or a list of strings.
> **NOTE**
> 
> This change will not go into affect in OpenShift CI until the rest of the "release-v2" feature and change requests are complete.
=> [Issue 52] Force jira_component to be a list of strings

README.md, cli/objects/configuration.py, cli/objects/jira_base.py, cli/objects/rule.py, cli/report/__init__.py, cli/report/report.py, docs/cli_usage_guide.md, docs/configuration_guide.md, tests/unittests/test_firewatch_report.py
This PR will migrate the "report success" functionality from PR #77 out of the firewatch config rules and into a CLI flag (`--report-success`) that makes use of the `$FIREWATCH_DEFAULT_*` environment variables. 
I have done this promote uniform rules in the firewatch config. Considering this functionality is set at the job level rather than on a per step/failure-type basis, I feel it is more suited to a CLI flag.
1. Set the following environment variables (and all other config values that are normally set):
- `FIREWATCH_DEFAULT_JIRA_PROJECT` [REQUIRED]: This value should already be set anyway, it is not a new piece of the functionality. This is the Jira project where the story will be created
- `FIREWATCH_DEFAULT_JIRA_EPIC` [OPTIONAL]: This is an optional environment variable that can be …
=> [Issue #100] Move the "report success" functionality configuration to a flag that utilizes `$FIREWATCH_DEFAULT_*` environment variables

cli/report/__init__.py, cli/report/report.py, docs/contribution_guide.md
The DPTP team is moving all artifacts to the test-platform-results GCS bucket. This is happening today, this PR should be merged following the completion of the task.
DPTP comms about this change: https://redhat-internal.slack.com/archives/CFUGK0K9R/p1704920416570079
=> [Urgent Change] Update the default gcs bucket to test-platform-results per DPTPs change.

README.md, cli/objects/jira_base.py
We have noticed when adding a new label to an already existing issue in Jira that the permissions on the `firewatch-tool` user needed to be updated in our projects. This PR adds some logging around this issue to help users who may not be familiar with the problem. It also adds some specific documentation to the README to help resolve the problem or tell new users what is required before using the tool.
Closes #148
=> [#148] Add try/except block around code adding labels to already existing issues

cli/objects/failure_rule.py
Fixes #151
See [INTEROP-7264](https://issues.redhat.com/browse/INTEROP-7264)
=> revert changes to failure matching logic in failure_rule.py.

cli/objects/job.py
Context:
If the test results file contains a broken XML content, the [junitparser command](https://github.com/RedHatQE/firewatch/blob/main/cli/objects/job.py#L420) will fail with a:
`xml.etree.ElementTree.ParseError: syntax error: ..` failure.
See job failure example: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.15-lp-interop-mtc-interop-aws/1756921885850865664#1:build-log.txt%3A93
This happens especially when we modify the test results with replacing it's content with a string contains:
`"This file contained potentially sensitive information and has been removed.\\n"
`
REF:
https://redhat-internal.slack.com/archives/C04PK4QPSR1/p1707747454327419
=> Catch xml.etree.ElementTree ParseError exception from an invalid XML file

src/report/report.py
The URL that was getting logged was incorrect in one location and was missing a /
This updates the URL to be correct
=> Correct URL getting logged to be the right address

src/objects/job.py, tests/e2e/conftest.py, tests/e2e/templates/jira_configs/jira.config.j2, tests/unittests/conftest.py, tests/unittests/objects/job/test_fail_with_test_failures_should_not_cause_failure_for_ignored_step.py
log warning message when ignored failures are marked.
fix and update unittests for bug #133.
add e2e test for bug #133.
fixes #133
see [LPTOCPCI-1202](https://issues.redhat.com/browse/LPTOCPCI-1202)
=> Fix #133: prevent further handling of failures marked as ignored

src/report/report.py, tests/unittests/functions/report/test_firewatch_functions_report_failure_matches_rule.py
Currently, if we have more then one matching rule for a failure, the code will take the first rule matched and consider the second a "duplicate" ticket.
**The goal** is to prioritize it with first check if there's a rule with the same name, otherwise use patterns or duplication.
Workflow example: 
1. We have two rules defined, one for exact- and one for exact-step. But, the rule for `exact-*` is first in the list of rules and `exact-step` is second.
2. A failure in `exact-step` is identified and paired with both rules.
3. In [this for loop](https://github.com/RedHatQE/firewatch/blob/main/src/report/report.py#L136), the first pair (`exact-*` rule) generates a bug.
4. In the second iteration of the for loop, the failure pair with the exact-step rule does not generate a ticket, since it'll …
=> Add hierarchy to handle multiple matching rules for a failure

.pre-commit-config.yaml, src/objects/configuration.py, tests/unittests/functions/report/test_firewatch_functions_report_failure_matches_rule.py, tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_config_data.py
For occurring steps and workflows in our project, we want to initialize a source that holds our Firewatch base config.
Once set up (optional), our Openshift-ci env `FIREWATCH_CONFIG` values will be added on top of that.
This PR allows the user to override the base config by:
-  replacing steps with general patterns with specific step names and vice versa
-  updating existing rules with new logic. 
For example: 
The team consistently uses the rule `{"step": "failure", "ignore": "True"...}` and holds it in their base config file; a specific scenario might need to override it and set the "ignore" to "False".
in this case, the scenario will mention this step in their `FIREWATCH_CONFIG` env var.
Unit-tests main additions:
- steps containing patterns and steps that matches them are co-existing …
=>  Add support for Firewatch base config

src/commands/report.py, src/objects/configuration.py
Main changes:
1. Remove strict Click requirement for Firewatch config path to be an existing file
- The cli accepts URLs
2. Allow the Firewatch configuration to include rules without "step"
- Example:
```
"success_rules":
[
{"jira_project": "PROJECT", "jira_additional_labels": ["!default"]}
]
```
=> Remove cli requirement for existing path, allow configuration rules without "step"

docs/cli_usage_guide.md
Fix guide links and container command in cli usage guide
=> Update CLI usage guide 

src/report/constants.py, src/report/report.py, tests/unittests/objects/job/test_firewatch_objects_job_check_is_retriggered.py
Fix the label name and usage.
Label applied to all open bug that job is retriggered in current week
Also updated the unit test, as the mock_datetime was not working as expected
=> Update retrigger label, logic & fix unit test

src/objects/job.py
The full path to started.json (which contains job timestamp) needs to include the logs in path.
Otherwise [such error](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-oadp-qe-oadp-qe-automation-oadp-1.4-oadp1.4-ocp4.19-lp-interop-oadp-interop-aws/1911662362113347584/artifacts/oadp-interop-aws/firewatch-report-issues/build-log.txt) is generated
=> Fix the timestamp path
